---
title: "PCA"
output: html_document
date: "2024-06-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data read-in and pre-processing

```{r}
setwd('/home/newuser/Desktop/Rworks')
getwd()

df <- read.csv('pca.eu40.vs.dchry2.3.autosome.DP8_100.GQ20.4dsites.rm1.csv')
meta <- read.csv('metadata_detailed.csv')

meta$Region_col <- c(rep(1,28),rep(2,12)) #index correspnding regions
match(df$id,meta$Sample.ID) #see if the output sample IDs match those from metadata
df2 <- merge(df,meta,by.x = 'id',by.y = 'Sample.ID') #merge two tables by sample IDs

var_exp <- read.table('pca.eu40.vs.dchry2.3.autosome.DP8_100.GQ20.4dsites.rm1.explained_variance.txt', header = T) # read in the text file with percntage of varaince explained
var_exp$variance_explained <- round(var_exp$variance_explained,3)*100
```

Import metadata from original xlsx file and output metadata table with detailed locations (don't run)

```{r}
library(readxl)

meta <- read_xlsx('chrysippus_RVcoll_sequenced_African_added.xlsx',col_names = T,range = 'A1:Q42')
meta <- meta[!is.na(meta$`Sample ID`),] #exclude the empty rows
meta$Region <- c(rep('Mediterranean',28),rep('African',12)) #create a column for region
meta$Region_col <- c(rep(1,28),rep(2,12)) #index correspnding regions
df2 <- merge(df,meta,by.x = 'id',by.y = 'Sample.ID') #merge two tables by sample IDs

meta$Narrow_regions <- meta$`State~ Province`

for (i in 1:nrow(meta)) {
  if (is.na(meta$Narrow_regions[i])) {
    meta$Narrow_regions[i] <- meta$Country[i]
  }
}
meta$Narrow_regions[meta$Narrow_regions == "M'sila"] <- "Algeria"
meta$Narrow_regions[meta$Narrow_regions == "Balearic Islands"] <- "Mallorca" #create the appropriate names for the sample locations, consistent to those in proposal
meta$Region <- c(rep('Mediterranean',28),rep('African',12))
write.csv(meta[,c('Sample ID','Region','Narrow_regions')],file = 'metadata_detailed.csv',row.names = F)
```

## Plotting a draft for first view

```{r}
plot(df2[,'PC1'],df2[,'PC2'],pch = 3,col = df2$Region_col, cex = 0.5,
     xlab = 'PC1',ylab = 'PC2',main = 'PCA results of SNPs from whole dataset')
```

## Plotting with legends and labels

```{r}
#adjust the legend position according to the space on the plot

png(filename = 'PCA_autosome_rm1.png',res = 300,width = 200, height = 160, units = 'mm') #plot the PCA results with higher resolution. n.b. the parameters should be stated when using this command

plot(df2[,'PC1'],df2[,'PC2'],pch = 3,col = df2$Region_col, cex = 0.5,
     xlab = paste('PC1,',var_exp$variance_explained[1],'% variance explained'),
     ylab = paste('PC2,',var_exp$variance_explained[2],'% variance explained'),
     main = 'PCA results of total population from all autosomes, one relative removed')
legend(300,-100,legend = unique(df2$Region),col = unique(df2$Region_col), cex = 0.7,pch = 3) #add figure legends

dev.off()
```

## Specify the regions in more detail

```{r}
region_num <- length(unique(df2$Narrow_regions))
cl <- palette.colors(n=region_num) #create distinctive colors to be plotted in the PCA for each group.
plot(seq(1,region_num),rep(0,region_num),col = palette.colors(n=region_num)) #preview these colors in a plot
df2$Narrow_regions_num <- 0
for (i in 1:region_num) {
  df2$Narrow_regions_num[df2$Narrow_regions == unique(df2$Narrow_regions)[i]] <- cl[i]
} #assign the corresponding color names to the geographic locations

table(df2$Narrow_regions_num)
```

```{r}
# Detect the outliers from the plot
#outlier_pc1 <- df2[df2$'PC1' < -2000,] #Ghana ones that are probably relatives
#outlier_pc2 <- df2[df2$id %in% c('RV22454','RV22453'),] #Fake? outliers from advance PCA on chr30
```

## Plot the detailed region groups in the same PCA plot

```{r}
#adjust the legend position according to the space on the plot

png(filename = 'PCA_autosome_rm1_detailed_pc2vs3.png',res = 300,width = 200, height = 160, units = 'mm') #plot the PCA results with higher resolution. n.b. the parameters should be stated when using this command

plot(df2[,'PC2'],df2[,'PC3'],pch = 3,col = df2$Narrow_regions_num, cex = 0.5,
     xlab = paste('PC2,',var_exp$variance_explained[2],'% variance explained'),
     ylab = paste('PC3,',var_exp$variance_explained[3],'% variance explained'),
     main = 'PCA results of total population from autosome, detailed region groups')
legend(0,600,legend = unique(df2$Narrow_regions),col = unique(df2$Narrow_regions_num), cex = 0.7,pch = 3) #add figure legends
#text(outlier_pc1[,'PC1'],outlier_pc1[,'PC2'],outlier_pc1[,'id'],cex = 0.5, pos = 4) #label the name of outlier from African group
#text(outlier_pc2[,'PC1'],outlier_pc2[,'PC2'],outlier_pc2[,'id'],cex = 0.5, pos = 4) #label the name of outliers from Mediterranean group


dev.off()
```
