---
title: "Plot_ROH"
output: html_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('~/Desktop/Rworks')
```

## Read bcftools roh results

```{r}
library(dplyr)
library(ggplot2)

df <- read.table('roh_result_rg')
colnames(df) <- c('RG','SampleID','chr','start','end','len','markers','qual')
head(df)
table(df$SampleID)
meta <- read.csv('metadata_detailed.csv')
chrom_length <- sum(read.table('chromosome_length')) #extract the autosome length
```

### Calculate the F(ROH) based on total ROH region length

```{r}
total_roh_length <- df %>%
  group_by(SampleID) %>%
  summarise(total_length = sum(len, na.rm = TRUE))
total_roh_length_m <- merge(total_roh_length,meta,by.x = 'SampleID',by.y = 'Sample.ID')
total_roh_length_m$Froh <- total_roh_length_m$total_length/chrom_length

#Average F(ROH) for both populations
f_roh_med <- mean(total_roh_length_m[total_roh_length_m$Region == 'Mediterranean','Froh'])
f_roh_Afr <- mean(total_roh_length_m[total_roh_length_m$Region == 'African','Froh'])

#generate a summarising barplot for each individual
labels_f <- sort(total_roh_length_m$Froh)
t <- total_roh_length_m[match(labels_f,total_roh_length_m$Froh),]

total_roh_length_m_sorted <- total_roh_length_m %>%
  mutate(SampleID = reorder(factor(SampleID), Froh))

png(filename = 'ROH_Froh_indiv.png',res = 300,width = 200, height = 160, units = 'mm')
ggplot(total_roh_length_m_sorted, aes(x = SampleID, y = Froh, fill = Region)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Locations from which individuals are sampled", y = "F(ROH)") +
  theme_minimal() +
  scale_x_discrete(labels = t$Narrow_regions) +
  theme(axis.text.x = element_text(size = 7, angle = 45, hjust = 1, vjust = 1.2))
dev.off()

island <- c('Mallorca','Canary Islands')
froh_island <- total_roh_length_m_sorted[total_roh_length_m_sorted$Narrow_regions %in% island,'Froh']
froh_mainland <- total_roh_length_m_sorted[!(total_roh_length_m_sorted$Narrow_regions %in% island)&(total_roh_length_m_sorted$Region == 'Mediterranean'),'Froh']
t_test <- t.test(froh_island,froh_mainland)
```

### Plot the histogram to summarize distribution of ROH regions

```{r}
library(ggplot2)

#Label samples according to population groups
df_m <- merge(df,meta,by.x = 'SampleID',by.y = 'Sample.ID')

sampleID_Med <- meta[meta$Region == 'Mediterranean','Sample.ID']
sampleID_Afr <- meta[meta$Region == 'African','Sample.ID']
df_Med <- df[df$SampleID %in% sampleID_Med,]
df_Afr <- df[df$SampleID %in% sampleID_Afr,]

#Divide the data for populations
df_m_Med <- df_m[df_m$Region == "Mediterranean",]
df_m_Afr <- df_m[df_m$Region == "African",]

# Plot the histograms with scaled counts
png(filename = 'ROH_distribution_pops.png',res = 300,width = 200, height = 160, units = 'mm')
ggplot() +
  geom_histogram(
    data = df_m_Med, aes(x = len, y = ..count.. / length(sampleID_Med), fill = Region),
    position = "identity", alpha = 0.5, binwidth = 2000
  ) +
  geom_histogram(
    data = df_m_Afr, aes(x = len, y = ..count.. / length(sampleID_Afr), fill = Region),
    position = "identity", alpha = 0.5, binwidth = 2000
  ) + #input for y-axis are scaled counts within each bin
  xlim(2000,1.5e05) + #small stretches of ROH are removed because they could be created by chance.
  scale_y_continuous("Scaled Count") +
  labs(x = "ROH length") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c("Mediterranean" = "blue", "African" = "red"))
dev.off()
```
